name: Pebble snap

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pebble repo
        uses: actions/checkout@v2

      - name: Build Pebble Snap
        id: build-pebble-snap
        uses: snapcore/action-build@v1
        with:
          path: pebble

      - name: Attach pebble snap to GH workflow execution
        uses: actions/upload-artifact@v2
        with:
          name: pebble.snap
          path: ${{ steps.build-pebble-snap.outputs.snap }}