name: Pebble snap

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pebble repo
        uses: actions/checkout@v2
      
      - name: test
        run: |
          ls -a
          git status
          git describe --always



      - name: Build Pebble Snap
        id: build-pebble-snap
        uses: snapcore/action-build@v1

      - name: Attach pebble snap to GH workflow execution
        uses: actions/upload-artifact@v2
        with:
          name: pebble.snap
          path: ${{ steps.build-pebble-snap.outputs.snap }}